### ISSUE TITLE
Anyway of speeding this up

### ISSUE THREAD

**Issue by pssguy** [cpsievert/rdom#4]
Extremely promising but is there anyways to speed up the process

```
system.time(
df <- rdom("https://www.datatables.net/examples/data_sources/js_array.html") %>%
  html_node("#example") %>% html_table()
)

  user  system elapsed 
   0.10    0.15   36.27
```

That's a long wait for a 10x5 table!

**Comment by cpsievert** [comment]
Try doing this instead:

``` r
rdom("https://www.datatables.net/examples/data_sources/js_array.html", "#example") %>% html_table()
```

This way R doesn't have to parse the entire DOM, but it'll still take awhile because phantomjs has to open and fully render the page which is an expensive operation. 

If you're really concerned about performance, you might want to use the CLI instead ->
https://github.com/cpsievert/rdom#using-the-cli

**Comment by cpsievert** [comment]
Actually, this was probably taking a long time since the timeout was set at 30 seconds. I reduced this in 7c017d87f4d9b19ad0242fb9152a823d6b08d57d and will look into a smarter timeout setting

**Comment by pssguy** [comment]
Just downloaded again and re-run . Took 8 secs so quite the improvement. I will probably just want for scraping and then further processing offline so time is not that big an issue in this scenario
Thanks
